### ISSUE TITLE
To-dos 4/27/2024

### ISSUE THREAD

**Issue by shatayu** [shatayu/rl-collective-action#7]
- reformat to NeurIPS style
- add 3-4 new papers from NeurIPS
- change results section to better convey the magnitude of the results (see slides)
- add distributions (maybe 3D charts of distributions per round)
- plot showing percentage of plot over time
- create plot similar to the validation plot where X is AI contribution and Y is other baseline contribution

- are there other PGG papers with other interventions?

**Comment by sbrunswi** [comment]
- [x] reformat to NeurIPS style @shatayu 
- [x] add 3-4 new papers from NeurIPS @shatayu 
- [x] change results section to better convey the magnitude of the results: 
     - [x] show the distribution over time as boxplot (**resolved** by using confidence intervals)
     - [x] show the percentage of cooperatives over time; plot the 0.5 as the 0 -axis and show the deviation from the 0.5 benchmark
     - [x] Add a figure that shows the percentage increase rather than the absolute contribution increase
     - [x] Make sure you align with Sabine at 5 pm EST to clarify the nature of the plots
     - [x] Could we show the "path" of the individuals? rather than average? in the sense of scatter plots where we highlight the movements of those that stay beyond the 0.5; 
     - [x] Show the difference between the AI-agent and the contribution of those individuals that have a positive trend
     - [x] Show people with a positive trend
     - [ ] Can we articulate the inflection poitns? 
- [x] add distributions (maybe 3D charts of distributions per round)  see comments above
- [ ] plot showing percentage of plot over time - see comments above  see commentes above
- [x] create plot similar to the validation plot where X is AI contribution and Y is other baseline contribution GREAT
- [x] are there other PPG papers with other interventions?
- [x] Find papers ond descriptive norms @shatayu  (ideally a summary how much they shifted the contribution: e.g. increase by % is typically what is reported)
    * [Strategic reward and altruistic punishment support cooperation in a public goods game experiment](https://linkinghub.elsevier.com/retrieve/pii/S0167487013000032): " in the punishment treatment the average contribution level increases from 8.17 in the baseline phase to 12.51 in the partner phase. In the reward treatment, the average contribution rises from 9.38 in the baseline phase to 12.31 in the partner phase" (context: token size is 20 tokens per round, 10 rounds per phase and 3 phases total)

**Comment by shatayu** [comment]
All charts are computed in [the analysis notebook](https://colab.research.google.com/drive/1vWFJB_ZUUDheg_GozA62d-emsYvjwAqN#scrollTo=aISs8DppVGR7).
